### ISSUE TITLE
Get URL kind/resource type

### ISSUE THREAD

**Issue by IcySnex** [jerry08/SoundCloudExplode#3]
Hello,

When searching on SoundCloud, there are multiple methods that can be used depending on whether the URL is for a track, album, user, etc. Currently, there is no method in the `SoundCloudClient` to obtain an enum representing the URL kind/resource type.

The `SoundcloudEndpoint` class implements the `ResolveUrlAsync` method, which is already used internally by, for example, the `TrackClient`. However, the response from the resolve endpoint also contains a property called "kind" that indicates the resource type, such as "track," "playlist," or "user."

It would be very useful to have a method like `GetUrlKindAsync` directly in the SoundCloudClient, instead of having to create a new `SoundcloudEndpoint` and parse the response ourselves. I apologize if I am overlooking something, please let me know.

Kind regards,

**Comment by jerry08** [comment]
Hey. I just updated the repo with the changes you mentioned. You can review these 2 commits to make sure I didn't miss anything: 76457e4 and e458a15. If it looks good I'll update the NuGet package.

**Comment by IcySnex** [comment]
Yeah, that looks great! Thank you very much.
